# Generated by Django 6.1 on 2026-08-20 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('horario_uso', models.CharField(max_length=255)),
                ('permiso_mostrar', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'academias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'canchas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adelanto', 'Adelanto'), ('saldo', 'Saldo')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('individual', 'Media cancha'), ('completo', 'Campo completo')], max_length=20)),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'reserva_canchas',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('individual', 'Media cancha'), ('completo', 'Campo completo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('precio_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'tarifas',
                'ordering': ['modalidad', 'hora_inicio'],
            },
        ),
    ]
