# Generated by Django 6.1 on 2026-08-20 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='asignada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='reservacancha',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.cancha'),
        ),
        migrations.AddField(
            model_name='reservacancha',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas_asignadas', to='reservas.reserva'),
        ),
        migrations.AlterUniqueTogether(
            name='reservacancha',
            unique_together={('reserva', 'cancha')},
        ),
    ]
