# Generated by Django 6.1 on 2026-08-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_seed_canchas_tarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.academia'),
        ),
    ]
