# Generated by Django 6.1 on 2026-08-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_academia_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='academia_horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_generadas', to='reservas.academiahorario'),
        ),
    ]
