# Generated by Django 6.1 on 2026-08-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_reserva_academia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('ausente', 'No vino')], default='confirmada', max_length=20),
        ),
    ]
