# Generated by Django 6.1 on 2026-08-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='es_adelanto',
            field=models.BooleanField(default=False),
        ),
    ]
